name: All Tests
on:
  pull_request:
    # branches: [develop, master, milestone, dependabot-update]
jobs:
  all-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # - name: Install dependencies
      #   run: npm ci
      - name: Run vitest
        run: echo "npm run test:unit:all"
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npm run e2e:all
      # - name: Run generate
      #   run: npm run generate
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: all-tests-report
          path: all-tests-report/
          retention-days: 30
  merge-dependabot-PR:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: all-tests
    if: contains(github.head_ref, 'dependabot')
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Update pull request branch
        run: |
          curl "https://github.com/h-yabi/github-actions-test/pull/12" \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -d '{ "base": "main" }'
